INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (100,'víctormontoya@gmail.com','45216532');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (101,'joségomez@gmail.com','44459532');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (102,'juancayuela@gmail.com','43633663');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (103,'ana maríasobrino@gmail.com','42121212');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (104,'isabelfernanedez@gmail.com','47484848');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (105,'rodolfobaeza@gmail.com','40344343');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (106,'mirtadi nardo@gmail.com','49996936');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (107,'estebantoledo@gmail.com','43464947');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (108,'rauldel marmol@gmail.com','42003300');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (109,'monicabrito@gmail.com','40999989');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (110,'estefanialezama@gmail.com','42665588');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (111,'ceciliarodriguez@gmail.com','41878787');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (112,'melinaberge@gmail.com','43656565');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (113,'darioaquili@gmail.com','44776677');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (114,'josefinacalvi@gmail.com','44989838');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (115,'teodorogambino@gmail.com','46784545');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (116,'melisamassa@gmail.com','49393939');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (117,'agustinacifre@gmail.com','40404040');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (118,'gastonespacavento@gmail.com','42404349');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (119,'juan cruzespindola@gmail.com','48787779');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (120,'telmaramirez@gmail.com','40936382');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (121,'rosariogonzalez@gmail.com','45103212');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (122,'brendaboris@gmail.com','46009700');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (123,'jorgetermopilas@gmail.com','40888888');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (124,'gustavoplayadito@gmail.com','49998877');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (125,'natanaelrosamonte@gmail.com','45555555');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (126,'irmacruz de malta@gmail.com','43002020');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (127,'yaninahelmans@gmail.com','43984572');
INSERT INTO contacto_pacientes (`idCPacientes`,`email`,`telefono`) VALUES (128,'diego armandobolsonaro@gmail.com','42720828');
