INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (1,'ALERGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (2,'INMUNOLOGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (3,'ANESTESIOLOGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (4,'CARDIOLOGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (5,'HEMODINAMIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (6,'CIRUGIA CARDIOVASCULAR');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (7,'CIRUGIA GENERAL');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (8,'CIRUGIA PLASTICA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (9,'CLINICA MEDICA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (10,'DERMATOLOGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (11,'ENDOCRINOLOGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (12,'GASTROENTEROLOGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (13,'GINECOLOGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (14,'OBSTETRICIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (15,'HEMATOLOGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (16,'INFECTOLOGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (17,'NEUROLOGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (18,'NUTRICION');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (19,'OFTALMOLOGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (20,'ONCOLOGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (21,'PEDIATRIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (22,'PSIQUIATRIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (23,'ECOGRAFIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (24,'ORTOPEDIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (25,'OSTEOLOGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (26,'TRAUMATOLOGIA Y ORTOPEDIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (27,'UROLOGIA');
INSERT INTO especialidad (`idEspecialidad`,`nombre`) VALUES (28,'VARIOS / OTROS');
